// <auto-generated />
namespace FarmBook_v7.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GuidesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GuidesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201409170522044_GuidesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
